title: Mike Sturm
description: Productivity, Personal Growth, etc.
theme: just-the-docs

url: https://mikesturm.github.io/Wild-Onion

aux_links:
 # Template Repository: https://github.com/just-the-docs/just-the-docs-template

# Define Jekyll collections
collections:
  # Define a collection named "tests", its documents reside in the  directory
  posts:
    permalink: "/:collection/:path/"
    output: true


  # Define which collections are used in just-the-docs
  collections:
    # Reference the "tests" collection
    posts:
      # Give the collection a name
      name: Posts
      # Exclude the collection from the navigation
      # Supports true or false (default)
      nav_exclude: false
      # Fold the collection in the navigation
      # Supports true or false (default)
      nav_fold: true  # note: this option is new in v0.4
      # Exclude the collection from the search
      # Supports true or false (default)
      search_exclude: false